class Subtitles:
	def __init__(self,
		lang_code:str, lang_name:str,
		ext:str, url:str,
		autogenerated:bool=False
	):
		self.code = lang_code
		self.name = lang_name
		self.extension = ext
		self.url = url
		self.autogenerated = autogenerated

	@property
	def ext(self): return self.extension

	def __str__(self): return f"Subtitles({self.code}{'-auto' if self.autogenerated else ''}.{self.ext})"
	def __repr__(self): return str(self)


class SubtitlesManager:
	def __init__(self, subs_dict=None):
		self.subtitles = subs_dict or {}
	def parse(self, subtitles_dict=None, filter_orig=False):
		raw_subtitles = subtitles_dict or {}
		formats = ["srt", "vtt"]
		for k, v in raw_subtitles.items():
			if filter_orig and not (k.lower().endswith("-orig")): continue
			filtered = list(
				filter(
					lambda s: (s.get('ext') in formats) and (s.get('protocol') != "m3u8_native")
				, v)
			)
			if len(filtered) > 0:
				lang_code = k.lower().removesuffix("-orig")
				self.subtitles[lang_code] = []
				for sub in filtered:
					obj = Subtitles(
						lang_code=lang_code,
						lang_name=sub.get('name'),
						ext=sub.get('ext'),
						url=sub.get('url'),
						autogenerated=k.lower().endswith("-orig")
					)
					self.subtitles[lang_code].append(obj)
					
	def keys(self) -> tuple: return tuple(self.subtitles.keys())
	def items(self) -> dict: return dict(self.subtitles.items())
	def values(self) -> list: return [sub for sublist in self.subtitles.values() for sub in sublist]
	def get(self, lang_code:str) -> list:
		'''Get subtitles by iso-code | returns list of Subtitles() or []'''
		return self.subtitles.get(lang_code.lower(), [])

	def __str__(self): return f"Subtitles({len(self.subtitles)})"
	def __repr__(self): return str(self)
	def __len__(self): return len(self.subtitles)
	def __iter__(self): return iter(self.subtitles.items())

	def __add__(self, other):
		combined = {
			lang: subs.copy()
			for lang, subs in self.subtitles.items()
		}
		for lang, subs in other.subtitles.items():
			combined.setdefault(lang, []).extend(subs)
		return SubtitlesManager(combined)

	def filter(self,
		ext:str=None,
		lang:str=None,
		only_autogen:bool=None,
		no_autogen:bool=None,
		custom=None
	) -> "SubtitlesManager":
		def predicate(obj):
			if ext and obj.ext != ext:
				return False
			if lang and obj.code != lang.lower():
				return False
			if only_autogen and not obj.autogenerated:
				return False
			if no_autogen and obj.autogenerated:
				return False
			if custom and not custom(obj):
				return False
			return True

		filtered = {
			lang: new_subs
			for lang, subs in self.subtitles.items()
			if (new_subs := [obj for obj in subs if predicate(obj)])
		}
		return SubtitlesManager(filtered)
