class Subtitles:
	def __init__(self,
		lang_code:str, lang_name:str,
		ext:str, url:str,
		autogenerated:bool=False
	):
		self.code = lang_code
		self.name = lang_name
		self.extension = ext
		self.url = url
		self.autogenerated = autogenerated

	@property
	def ext(self): return self.extension

	def __str__(self): return f"Subtitles({self.code}{'-auto' if self.autogenerated else ''}.{self.ext})"
	def __repr__(self): return str(self)


class SubtitlesManager:
	def __init__(self, subtitles_dict=None, filter_orig=False):
		self.subtitles = {}
		raw_subtitles = subtitles_dict or {}
		formats = ["srt", "vtt"]
		for k, v in raw_subtitles.items():
			if filter_orig and not (k.lower().endswith("-orig")): continue
			filtered = list(
				filter(
					lambda s: (s.get('ext') in formats) and (s.get('protocol') != "m3u8_native")
				, v)
			)
			if len(filtered) > 0:
				lang_code = k.lower().removesuffix("-orig")
				self.subtitles[lang_code] = []
				for sub in filtered:
					obj = Subtitles(
						lang_code=lang_code,
						lang_name=sub.get('name'),
						ext=sub.get('ext'),
						url=sub.get('url'),
						autogenerated=k.lower().endswith("-orig")
					)
					self.subtitles[lang_code].append(obj)
					
	def keys(self) -> tuple: return tuple(self.subtitles.keys())
	def get(self, lang_code:str) -> list:
		'''Get subtitles by iso-code | returns list of Subtitles() or []'''
		return self.subtitles.get(lang_code.lower(), [])

	def all(self) -> list:
		return [sub for sublist in self.subtitles.values() for sub in sublist]

	def __str__(self): return f"Subtitles({len(self.subtitles)})"
	def __repr__(self): return str(self)
	def __len__(self): return len(self.subtitles)
	def __iter__(self): return iter(self.subtitles.items())

	def __add__(self, other):
		combined_subs = {}

		for lang, subs in self.subtitles.items():
			combined_subs[lang] = subs.copy()

		for lang, subs in other.subtitles.items():
			if lang in combined_subs:
				combined_subs[lang].extend(subs)
			else:
				combined_subs[lang] = subs.copy()

		new_manager = SubtitlesManager()
		new_manager.subtitles = combined_subs
		return new_manager

	def clean(self) -> "SubtitlesManager":
		"""Return a new SubtitlesManager without autogenerated subtitles"""
		new_subs = {}

		for lang, subs in self.subtitles.items():
			filtered = [s for s in subs if not s.autogenerated]
			if filtered: new_subs[lang] = filtered

		new_manager = SubtitlesManager()
		new_manager.subtitles = new_subs
		return new_manager
